# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [28]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [29]:
print(np.__version__)

1.23.3


#### 3. Create a null vector of size 10 (★☆☆)

In [30]:
coords = []
for i in range(10):
    coords.append(0)

null_vector = np.array(coords)

print(null_vector)

#or

null_vector_2 = np.zeros(10)
print(null_vector_2)

[0 0 0 0 0 0 0 0 0 0]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [31]:
print(null_vector.size * null_vector.itemsize)

40


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [32]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [33]:
coords.clear()
for i in range(10):
    coords.append(0 if i != 4 else 1)

null_vector = np.array(coords)

print(null_vector)

[0 0 0 0 1 0 0 0 0 0]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [34]:
random_array = np.linspace(10, 49, 10, dtype = int)
print(random_array)

random_array = np.arange(10, 49, 1)
print(random_array)

[10 14 18 23 27 31 36 40 44 49]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [35]:
rev_vector = np.array([0,1,2,3,4,5,6,7,8,9])
print(np.flip(rev_vector))

[9 8 7 6 5 4 3 2 1 0]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [36]:
matrix = np.arange(0,9,1)
matrix.shape = (3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [37]:
nums = np.array([1,2,0,0,4,0])
indices = np.where(nums != 0)

print(indices[0])

[0 1 4]


#### 11. Create a 3x3 identity matrix (★☆☆)

In [38]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [39]:
print(np.random.randint(0, 9, size=(3,3,3)))

[[[5 0 2]
  [2 1 2]
  [8 6 3]]

 [[1 5 4]
  [4 2 7]
  [1 8 2]]

 [[7 6 4]
  [0 0 7]
  [2 0 4]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [40]:
matrix = np.random.randint(0, 1001, size=(10, 10))

min = np.min(matrix)
max = np.max(matrix)

print(f"Matrix:\n{matrix}\nMin: {min}\nMax: {max}\n")

Matrix:
[[303  42 693 342 398 137 222 353 447 470]
 [699 249 394 563 240 210 997 545 623 945]
 [553 159 780 975 348 832 455 774  70 219]
 [822 508 409 983 394 411 425 865 967  94]
 [617 803 677 881 140 483 564 897  13 714]
 [798 712 717 242 984 961 429 802 186 219]
 [349 195  48 634 988 299 344 340 172  31]
 [505 576 148 788 987 987  22 561 976 946]
 [331  77  18 589 787 822 485 887 188 460]
 [280 783 325 431 447  27 760 739 474 199]]
Min: 13
Max: 997



#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [41]:
rand_vector = np.random.randint(0, 1001, 30)
print(f"{rand_vector}\n{np.mean(rand_vector)}")

[756  21 884  72 362 807 547 942 673  36 647 416 446 752 638 494  64 630
 894 515 528 601 737 364 271 544 548 134 500 459]
509.4


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [42]:
square_matrix = np.zeros((5,5))
square_matrix[:, 0] = 1
square_matrix[0, :] = 1
square_matrix[:, square_matrix[0].shape[0] - 1] = 1
square_matrix[square_matrix.shape[1] - 1, :] = 1
print(square_matrix)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [43]:
square_matrix = np.pad(square_matrix, 1, constant_values=0)
print(square_matrix)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [44]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [45]:
some_new_matrix = np.diag(np.arange(1, 5, 1), k = -1)

print(some_new_matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [46]:
checkerboard = np.ones((8,8))
checkerboard[0:checkerboard.shape[0]:2,::2] = 0
checkerboard[1::2, 1:checkerboard.shape[0]:2] = 0
print(checkerboard)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [47]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [48]:
print(np.tile(np.array([[0,1],[1,0]]), (4,4)))

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [49]:
rand_matrix = np.random.randint(0, 100, size=(5, 5))
print(rand_matrix)
matrix_max = rand_matrix.max()
matrix_min = rand_matrix.min()
matrix_normalized = (rand_matrix - matrix_max)/(matrix_max - matrix_min)
print(matrix_normalized)

[[58 31 17 51 16]
 [15 79  6 43 73]
 [ 9 69 43 27 61]
 [49 78 93 22 25]
 [81  9 55 19 69]]
[[-0.40229885 -0.71264368 -0.87356322 -0.48275862 -0.88505747]
 [-0.89655172 -0.16091954 -1.         -0.57471264 -0.22988506]
 [-0.96551724 -0.27586207 -0.57471264 -0.75862069 -0.36781609]
 [-0.50574713 -0.17241379  0.         -0.81609195 -0.7816092 ]
 [-0.13793103 -0.96551724 -0.43678161 -0.85057471 -0.27586207]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [50]:
rgba = np.dtype({'names': ['r','g','b','a'], 'formats': [np.uint8, np.uint8, np.uint8, np.uint8]})
color = np.array([(255, 188, 32, 55)], dtype=rgba)
print(color)

[(255, 188, 32, 55)]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [51]:
mat_A = np.random.randint(0, 30, size=(5, 3))
mat_B = np.random.randint(0, 30, size=(3, 2))

print(mat_A.dot(mat_B))

[[1008  334]
 [1437  859]
 [1053  555]
 [ 915  406]
 [ 885  335]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [52]:
neg_array = np.array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
neg_array[(neg_array > 3) & (neg_array < 8)] *= -1

print(neg_array)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [53]:
9
10

10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [54]:
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1

NameError: name 'Z' is not defined

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [55]:
#invalid value encountered in divide
#divide by zero
np.array([np.nan]).astype(int).astype(float)

array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [56]:
array = np.array([1.34,2.44,3.22,4.44,5.55])
round_arr = np.round(array)
print(round_arr)

[1. 2. 3. 4. 6.]


#### 30. How to find common values between two arrays? (★☆☆)

In [57]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([5,6,7,8,9,10])

print(np.intersect1d(arr1, arr2))

[5 6]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [58]:
#np.seterr(all="ignore")

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [59]:
#no

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [60]:
today = np.datetime64('today')
yesterday = np.datetime64('today') - np.timedelta64(1, 'D')
tomorrow = np.datetime64('today') + np.timedelta64(1, 'D')

print(f"today: {today}\nyesterday: {yesterday}\ntomorrow: {tomorrow}\n")

today: 2022-10-31
yesterday: 2022-10-30
tomorrow: 2022-11-01



#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [61]:
print("July 2016")
print(np.arange('2016-07', '2016-08', dtype='datetime64[D]'))

July 2016
['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [62]:
mat_A = np.random.randint(0, 30, size=(5, 5))
mat_B = np.random.randint(0, 30, size=(5, 5))

print(np.add(mat_A, mat_B).dot(-mat_A / 2))

[[-1024.  -1172.   -852.  -1317.5 -1312.5]
 [-1509.  -1064.5 -1113.5 -1496.  -1708.5]
 [ -924.5 -1214.   -844.  -1398.  -1404. ]
 [ -906.   -921.   -770.  -1021.  -1082. ]
 [-1528.5 -1464.  -1011.  -1533.  -1737. ]]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [63]:
arr = np.random.randint(0, 30, 36)

print(np.floor(arr))
print(np.ceil(arr)-1)
print(np.trunc(arr))
print(arr.astype(int))
print(arr - arr%1)

[24. 28. 29. 22. 23. 20. 29. 22. 16. 13. 16.  4. 19.  9.  1. 22. 26. 29.
  9. 12. 17. 14. 27. 27. 19.  3.  4. 12.  9. 20.  2.  7. 25.  3. 29. 29.]
[23. 27. 28. 21. 22. 19. 28. 21. 15. 12. 15.  3. 18.  8.  0. 21. 25. 28.
  8. 11. 16. 13. 26. 26. 18.  2.  3. 11.  8. 19.  1.  6. 24.  2. 28. 28.]
[24. 28. 29. 22. 23. 20. 29. 22. 16. 13. 16.  4. 19.  9.  1. 22. 26. 29.
  9. 12. 17. 14. 27. 27. 19.  3.  4. 12.  9. 20.  2.  7. 25.  3. 29. 29.]
[24 28 29 22 23 20 29 22 16 13 16  4 19  9  1 22 26 29  9 12 17 14 27 27
 19  3  4 12  9 20  2  7 25  3 29 29]
[24 28 29 22 23 20 29 22 16 13 16  4 19  9  1 22 26 29  9 12 17 14 27 27
 19  3  4 12  9 20  2  7 25  3 29 29]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [64]:
print(np.tile(np.arange(5), (5,1)))

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [65]:
def generate(size):
    for i in range(size):
        yield i
        
array = np.fromiter(generate(10),dtype=int)
print(array)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [66]:
vector = np.linspace(0,1,11,endpoint=False)[1:]
print(vector)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [67]:
vector = np.random.randint(0, 30, 10)
vector.sort()
print(vector)

[ 0  6  9 16 17 17 21 21 23 28]


#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [68]:
A = np.random.randint(0, 30, 10)
B = np.random.randint(0, 30, 10)

print(np.array_equal(A,B))

A = np.array([7,2,3,4,1])
B = np.array([7,2,3,4,1])

print(np.array_equal(A,B))

False
True


#### 43. Make an array immutable (read-only) (★★☆)

In [69]:
read_only = np.random.randint(0, 30, 10)
read_only.flags.writeable = False
read_only[0] = 15

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [70]:
cartesian_coords = np.random.random((10,2))

x_coords = cartesian_coords[:,0]
y_coords = cartesian_coords[:,1]

r_coords = np.sqrt(x_coords ** 2 + y_coords ** 2)
theta_coords = np.arctan2(y_coords,x_coords)

print(f"r: {r_coords}\n\ntheta:{theta_coords}")

r: [0.98473836 0.94186382 0.07622702 0.89505547 0.86368467 1.23367626
 0.88060932 0.28067132 1.17165221 1.1915353 ]

theta:[1.05173005 0.30064669 1.07072525 0.77886271 1.17847612 0.9352773
 0.27782388 1.34054276 0.91194863 0.72714807]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [71]:
vector = np.random.randint(0, 30, 10)

print(vector)

vector[np.where(vector == vector.max())] = 0

print(vector)

[ 1 16  9 29 28 13 17 27  6 20]
[ 1 16  9  0 28 13 17 27  6 20]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [72]:
coords = np.zeros((5,5), [('x',float),('y',float)])

coords['x'], coords['y'] = np.meshgrid(np.linspace(0,1,5), np.linspace(0,1,5))
print(coords)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [73]:
X_arr = np.random.randint(0, 30, 10)
Y_arr = np.random.randint(0, 30, 10)

X_arr = X_arr.reshape((-1,1))

diff_matrix = X_arr - Y_arr

cauchy_matrix = 1.0 / diff_matrix
print(cauchy_matrix)

[[ 0.08333333  0.03846154  0.09090909  0.16666667  0.03703704  0.1
   0.04761905  0.5         0.04        0.07692308]
 [-0.1         0.25       -0.09090909 -0.0625      0.2        -0.08333333
  -1.         -0.05        0.33333333 -0.11111111]
 [ 0.08333333  0.03846154  0.09090909  0.16666667  0.03703704  0.1
   0.04761905  0.5         0.04        0.07692308]
 [-0.14285714  0.14285714 -0.125      -0.07692308  0.125      -0.11111111
   0.5        -0.05882353  0.16666667 -0.16666667]
 [ 0.08333333  0.03846154  0.09090909  0.16666667  0.03703704  0.1
   0.04761905  0.5         0.04        0.07692308]
 [-0.08333333  0.5        -0.07692308 -0.05555556  0.33333333 -0.07142857
  -0.33333333 -0.04545455  1.         -0.09090909]
 [-0.09090909  0.33333333 -0.08333333 -0.05882353  0.25       -0.07692308
  -0.5        -0.04761905  0.5        -0.1       ]
 [ 0.07692308  0.03703704  0.08333333  0.14285714  0.03571429  0.09090909
   0.04545455  0.33333333  0.03846154  0.07142857]
 [ 0.125       0.0454

C:\Users\Vitalii\AppData\Local\Temp\ipykernel_12784\338302039.py:8: RuntimeWarning: divide by zero encountered in divide
  cauchy_matrix = 1.0 / diff_matrix


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [74]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [75]:
array = np.random.randint(0, 30, 10)
print(array)

[25  4 14 11 17 20  8  6  8  8]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [76]:
vector = np.random.randint(0, 30, 10)
scalar = np.random.randint(30)

index = (np.abs(vector-scalar)).argmin()
print(f"Closest value to scalar: {scalar} is value: {vector[index]} with index: {index} from vector:\n{vector}")

Closest value to scalar: 5 is value: 8 with index: 5 from vector:
[10 26 13 23 21  8 25 19  1 24]


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [77]:
rgb_pos_dt = np.dtype([
    ('position', [ 
        ('x', 'f4'),
        ('y', 'f4')
    ]),
    ('color', [
        ('r', 'u1'),
        ('g', 'u1'),
        ('b', 'u1')
    ])
])


matrix = np.zeros((6,3), rgb_pos_dt)
print(matrix)

[[((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0))]
 [((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0))]
 [((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0))]
 [((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0))]
 [((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0))]
 [((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0))]]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [78]:
vector = np.random.random((100,2))

x, y = np.atleast_2d(vector[:,0], vector[:,1])
distance = np.sqrt( (x-x.T)**2 + (y-y.T)**2)

print(distance)


[[0.         0.34377313 0.18625301 ... 0.46828382 0.79629496 0.63754701]
 [0.34377313 0.         0.52220297 ... 0.46018298 0.83823887 0.29572813]
 [0.18625301 0.52220297 0.         ... 0.51093673 0.76793801 0.81038661]
 ...
 [0.46828382 0.46018298 0.51093673 ... 0.         0.37843673 0.59449102]
 [0.79629496 0.83823887 0.76793801 ... 0.37843673 0.         0.93568475]
 [0.63754701 0.29572813 0.81038661 ... 0.59449102 0.93568475 0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [79]:
array = np.arange(10, dtype=np.float32)

array = array.astype(np.int32, copy=False)

print(array)

[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [80]:
from io import StringIO


some_file = StringIO("""1, 2, 3, 4, 5\n
                        6,  ,  , 7, 8\n
                         ,  , 9,10,11\n""")

imported_array = np.genfromtxt(some_file, delimiter=",", dtype=int)
print(imported_array)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [81]:
matrix = np.random.randint(0, 30, size=(3,3))

for index, value in np.ndenumerate(matrix):
    print(index, value)
    
for index in np.ndindex(matrix.shape):
    print(index, matrix[index])

(0, 0) 26
(0, 1) 5
(0, 2) 16
(1, 0) 15
(1, 1) 25
(1, 2) 16
(2, 0) 11
(2, 1) 10
(2, 2) 13
(0, 0) 26
(0, 1) 5
(0, 2) 16
(1, 0) 15
(1, 1) 25
(1, 2) 16
(2, 0) 11
(2, 1) 10
(2, 2) 13


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [82]:
x, y = np.meshgrid(np.random.random(10), np.random.random(10))

sigma = 1.0 
mu = 0.0

gaussian = np.exp(-((np.sqrt(x*x+y*y)-mu)**2/(2.0 * sigma**2)))
print(gaussian)



[[0.55734435 0.53218039 0.43032753 0.40574721 0.46571986 0.64132157
  0.60040563 0.45033542 0.45555728 0.63519339]
 [0.67332479 0.64292434 0.51987643 0.49018108 0.56263372 0.77477722
  0.72534689 0.54404786 0.55035636 0.7673738 ]
 [0.86216697 0.82324033 0.66568213 0.62765836 0.72043123 0.99207298
  0.9287793  0.69663274 0.70471053 0.98259317]
 [0.66902183 0.63881565 0.51655409 0.48704852 0.55903814 0.76982592
  0.72071147 0.54057106 0.54683924 0.7624698 ]
 [0.70775936 0.6758042  0.54646348 0.51524948 0.59140743 0.81440018
  0.76244193 0.57187107 0.57850219 0.80661814]
 [0.79416219 0.75830595 0.6131754  0.57815082 0.66360608 0.91382166
  0.85552036 0.64168474 0.64912538 0.90508958]
 [0.59948338 0.57241685 0.46286322 0.43642447 0.50093146 0.68980985
  0.64580038 0.48438385 0.49000051 0.68321833]
 [0.54290391 0.51839193 0.41917801 0.39523456 0.45365335 0.62470533
  0.58484949 0.43866751 0.44375407 0.61873592]
 [0.83287026 0.79526636 0.64306204 0.60633033 0.69595075 0.95836202
  0.89721908

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [83]:
matrix = np.zeros((10,10))
count_of_replacements = 1
replacer_num = 7
np.put(matrix, np.random.choice(matrix.size, count_of_replacements, replace=False), replacer_num)
print(matrix)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 7. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [84]:
matrix = np.random.randint(0, 30, size=(5,10))
mean = matrix - matrix.mean(axis=1, keepdims=True)

print(mean)

[[ 14.2   3.2  -0.8   9.2  -0.8   0.2  -6.8  -1.8  -7.8  -8.8]
 [ -8.3  13.7  12.7 -10.3  -9.3   5.7 -12.3  -8.3   5.7  10.7]
 [  6.8   3.8  -4.2  -3.2  -0.2  -2.2 -13.2  -2.2  14.8  -0.2]
 [ -2.2   0.8 -13.2  11.8   7.8   2.8  -2.2  -4.2   9.8 -11.2]
 [  6.7   7.7   3.7  -5.3  -5.3   5.7  -3.3 -15.3   5.7  -0.3]]


#### 59. How to sort an array by the nth column? (★★☆)

In [85]:
matrix = np.random.randint(0,30,(3,3))
print(matrix)
print(matrix[matrix[:,1].argsort()])

[[ 8 20 17]
 [19  5 19]
 [27 23 19]]
[[19  5 19]
 [ 8 20 17]
 [27 23 19]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [86]:
matrix = np.random.randint(0,3,(3,10))
print(matrix)
print((~matrix.any(axis=0)).any())

[[2 1 0 2 0 1 0 1 2 0]
 [1 0 1 2 2 0 1 1 2 2]
 [0 1 2 1 1 1 2 2 0 0]]
False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [87]:
array = np.random.randint(0,345,30)
value = 8
m = array.flat[np.abs(array - value).argmin()]
print(array)
print(m)

[338  68  27 317 300 219 280  90  99 323 336 309 339   1   9 284  58 293
   5 292  70 260  42  12 121 171 141 164  83 229]
9


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [88]:
arr_1 = np.random.randint(0,10,(1,3))
arr_2 = np.random.randint(0,10,(3,1))

iterator = np.nditer([arr_1, arr_2, None])

for x,y,z in iterator: z[...] = x + y

print(iterator.operands[2])

[[ 7  7  6]
 [ 9  9  8]
 [11 11 10]]


#### 63. Create an array class that has a name attribute (★★☆)

In [91]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    
    def __array_finalize__(self, obj):
        if obj is None: 
            return
        self.info = getattr(obj, 'name', "no name")
        
named_array = NamedArray(np.random.randint(0,10,30), "cooler array")

print(f"Name: {named_array.name}: {named_array}")


Name: cooler array: [8 2 1 7 3 5 7 5 7 7 0 8 6 6 5 1 9 0 6 8 8 5 6 1 6 3 7 9 3 4]


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [97]:
array = np.ones(10)
array_of_indices = np.random.randint(0,len(array),20)

print(array)
print(array_of_indices)
np.add.at(array, array_of_indices, 1)

print(array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[9 1 3 7 3 4 1 2 8 4 6 1 5 2 8 9 8 6 7 3]
[1. 4. 3. 4. 3. 2. 3. 3. 4. 3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [102]:
index_list = [4,5,1,4,1,3,5]

weights_arr_x = [1,2,3,4,5,6,7]

occurrences = np.bincount(index_list, weights_arr_x)

print(occurrences)

[0. 8. 0. 6. 5. 9.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [104]:
width = 32
height = 32

image = np.random.randint(0,2,(height,width,3)).astype(np.ubyte)

print(image)

sum_color_pixels = image[...,0]*(256*256) + image[...,1]*256 +image[...,2]
unique_count = len(np.unique(sum_color_pixels))

print(unique_count)

[[[0 1 0]
  [0 0 0]
  [0 1 1]
  ...
  [1 1 1]
  [0 1 1]
  [1 1 0]]

 [[1 1 1]
  [0 1 1]
  [1 1 0]
  ...
  [0 1 1]
  [1 0 1]
  [1 1 0]]

 [[0 1 0]
  [0 1 0]
  [1 1 1]
  ...
  [1 1 1]
  [0 1 1]
  [1 0 1]]

 ...

 [[1 0 1]
  [0 0 1]
  [1 0 1]
  ...
  [0 1 0]
  [1 1 1]
  [0 0 0]]

 [[1 0 0]
  [0 1 1]
  [1 0 0]
  ...
  [1 0 0]
  [1 1 0]
  [0 0 0]]

 [[1 1 1]
  [1 0 1]
  [0 1 0]
  ...
  [0 1 0]
  [0 0 0]
  [0 1 0]]]
8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [105]:
A = np.random.randint(0,30,(5,5,5,5))

sum = A.sum(axis=(-2,-1))
print(sum)

[[453 431 382 327 404]
 [391 375 423 356 390]
 [392 408 356 433 373]
 [419 333 360 359 291]
 [354 372 297 315 419]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [111]:
vector_D = np.random.rand(100)
index_array_S = np.random.randint(0,10,100)

sums = np.bincount(index_array_S, vector_D)
counts = np.bincount(index_array_S)

means = sums / counts

print(means)

[0.5785103  0.70139704 0.6182294  0.6136046  0.57608188 0.37482963
 0.64493114 0.45616407 0.46753388 0.48643124]


#### 69. How to get the diagonal of a dot product? (★★★)

In [113]:
vector_1 = np.random.randint(0,15,(5,5))
vector_2 = np.random.randint(0,15,(5,5))
 
print(np.diag(np.dot(vector_1, vector_2)))



[205 189 412 231 259]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [114]:
vector = np.array([1,2,3,4,5])

zeros_count = 3
zero_vector = np.zeros(len(vector) + (len(vector)-1) * (zeros_count))
zero_vector[::zeros_count+1] = vector

print(zero_vector)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [118]:
array_3d = np.ones((5,5,3)) * 5
array_2d = np.ones((5,5)) * 3

print(array_3d * array_2d[:,:,None])

[[[15. 15. 15.]
  [15. 15. 15.]
  [15. 15. 15.]
  [15. 15. 15.]
  [15. 15. 15.]]

 [[15. 15. 15.]
  [15. 15. 15.]
  [15. 15. 15.]
  [15. 15. 15.]
  [15. 15. 15.]]

 [[15. 15. 15.]
  [15. 15. 15.]
  [15. 15. 15.]
  [15. 15. 15.]
  [15. 15. 15.]]

 [[15. 15. 15.]
  [15. 15. 15.]
  [15. 15. 15.]
  [15. 15. 15.]
  [15. 15. 15.]]

 [[15. 15. 15.]
  [15. 15. 15.]
  [15. 15. 15.]
  [15. 15. 15.]
  [15. 15. 15.]]]


#### 72. How to swap two rows of an array? (★★★)

In [120]:
matrix = np.random.randint(0,15,(5,5))

print(f"{matrix}\n")

matrix[[0,1]] = matrix[[1,0]]

print(matrix)

[[ 1 12  5  0  4]
 [ 5 10  2 14  3]
 [12  7 13 11  5]
 [10  7 14  0 14]
 [11  9 13  9  3]]

[[ 5 10  2 14  3]
 [ 1 12  5  0  4]
 [12  7 13 11  5]
 [10  7 14  0 14]
 [11  9 13  9  3]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [126]:
faces = np.random.randint(0,100,(10,3))

faces = np.roll(faces.repeat(2,axis=1),-1,axis=1)
faces = faces.reshape(len(faces)*3,2)
faces = np.sort(faces,axis=1)

G = faces.view( dtype=[('p0',faces.dtype),('p1',faces.dtype)] )
G = np.unique(G)

print(G)

[( 7, 57) ( 7, 88) (10, 54) (10, 55) (23, 54) (23, 81) (27, 66) (27, 68)
 (30, 43) (40, 53) (40, 89) (43, 43) (46, 50) (46, 87) (50, 87) (53, 65)
 (53, 87) (53, 89) (54, 55) (54, 81) (57, 64) (57, 78) (57, 82) (57, 86)
 (57, 88) (64, 86) (65, 87) (66, 68) (78, 82)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [127]:
sorted_arr = np.bincount([1,1,2,3,4,4,6])

array = np.repeat(np.arange(len(sorted_arr)), sorted_arr)

print(array)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [133]:
num = 3

array = np.random.randint(0,30,20)
cumulative_sum = np.cumsum(array, dtype = float)
cumulative_sum[num:] = cumulative_sum[num:] - cumulative_sum[:-num]

print(cumulative_sum[num-1:]/num)

[24.         20.         17.         11.33333333 15.33333333 17.
 24.         23.66666667 24.         17.33333333 14.66666667 10.33333333
 18.         13.         10.66666667 11.66666667 11.         14.        ]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [143]:
from numpy.lib import stride_tricks

window = 3
array = np.random.randint(0,30,10)

shape = (array.size - window + 1, window)
strides = (array.itemsize, array.itemsize)

print(stride_tricks.as_strided(array, shape=shape, strides=strides))

[[18 11 15]
 [11 15 20]
 [15 20 14]
 [20 14 18]
 [14 18 10]
 [18 10 26]
 [10 26  2]
 [26  2  8]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [146]:
array = np.random.randint(0,2,100)
print(array)
print(f"{np.logical_not(array, out=array)}\n")


array = np.random.uniform(-1.0,1.0,100)
print(array)
print(np.negative(array, out=array))

[0 0 0 1 1 0 0 1 0 1 1 1 0 0 1 0 1 1 1 0 0 0 0 0 1 1 0 0 1 0 1 1 0 1 1 1 1
 0 1 1 0 0 0 0 1 1 0 1 0 1 1 1 0 0 0 1 1 0 0 0 0 1 1 1 0 1 1 1 1 1 0 0 1 1
 1 0 1 0 1 0 1 1 0 0 1 0 1 0 0 0 0 0 1 1 1 0 0 1 1 0]
[1 1 1 0 0 1 1 0 1 0 0 0 1 1 0 1 0 0 0 1 1 1 1 1 0 0 1 1 0 1 0 0 1 0 0 0 0
 1 0 0 1 1 1 1 0 0 1 0 1 0 0 0 1 1 1 0 0 1 1 1 1 0 0 0 1 0 0 0 0 0 1 1 0 0
 0 1 0 1 0 1 0 0 1 1 0 1 0 1 1 1 1 1 0 0 0 1 1 0 0 1]

[-0.6555314   0.54465524 -0.06634625  0.30909777 -0.44441651 -0.20828711
 -0.35330816  0.36134711 -0.225154   -0.74404303  0.07775977 -0.56409317
 -0.13439461  0.11272809  0.19723962  0.91137132  0.8036939  -0.4124873
 -0.77000677 -0.65385356 -0.42570156 -0.33365322  0.11672379  0.03710872
  0.9309643   0.19400957 -0.06199681 -0.70174922  0.2886902   0.35589082
  0.78866715  0.32747427  0.06187956 -0.22192838 -0.77201144 -0.62265344
  0.60049993  0.40462299  0.06830554  0.6834805   0.22668907  0.8317996
 -0.19578095 -0.85066012 -0.25900252 -0.68773164 -0.67431629 -0.55562897
  0.18282

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [148]:

lines_first_points = np.random.uniform(-10,10,(10,2))
lines_second_points = np.random.uniform(-10,10,(10,2))
other_points  = np.random.uniform(-10,10,( 1,2))

coord_diffs = lines_second_points - lines_first_points
distances = (coord_diffs**2).sum(axis=1)
params_T = -(
    (lines_first_points[:,0]-other_points[...,0])*coord_diffs[:,0] + 
    (lines_first_points[:,1]-other_points[...,1])*coord_diffs[:,1]
) / distances

params_T = params_T.reshape(len(params_T), 1)
line_point_coord_diffs = lines_first_points + params_T*coord_diffs - other_points

line_point_distances = np.sqrt((line_point_coord_diffs**2).sum(axis=1))

print(line_point_distances)


[13.36398414  2.91156944  4.87717251 10.19995375  6.6138477   1.63955191
  6.96068124  6.02764884  7.02766209  9.51484384]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [149]:
def distance(P0, P1, p):
    coord_diffs = lines_second_points - lines_first_points
    distances = (coord_diffs**2).sum(axis=1)
    params_T = -(
        (lines_first_points[:,0]-other_points[...,0])*coord_diffs[:,0] + 
        (lines_first_points[:,1]-other_points[...,1])*coord_diffs[:,1]
    ) / distances

    params_T = params_T.reshape(len(params_T), 1)
    line_point_coord_diffs = lines_first_points + params_T*coord_diffs - other_points
    return np.sqrt((line_point_coord_diffs**2).sum(axis=1))

lines_first_points = np.random.uniform(-10,10,(10,2))
lines_second_points = np.random.uniform(-10,10,(10,2))
other_points  = np.random.uniform(-10,10,( 1,2))

print(np.array([distance(lines_first_points,lines_second_points,p_i) for p_i in other_points]))

[[ 6.04139285  3.13764729  2.8842166   6.16226199 11.98376184  0.29540046
   0.5975588   0.70858162 11.23560833  2.12120307]]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

[slice(1, 5, None), slice(1, 5, None)]
[slice(0, 4, None), slice(0, 4, None)]


IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [ ]:
array = np.arange(1,15,dtype=np.uint32)
splitted_array = stride_tricks.as_strided(array,(11,4),(4,4))

print(splitted_array)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [161]:
matrix = np.random.uniform(0,1,(10,10))
m_order_matrix, size_matrix, n_order_matrix = np.linalg.svd(matrix) 
rank = np.sum(size_matrix > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array?

In [162]:
array = np.random.randint(0,10,50)
print(np.bincount(array).argmax())

2


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [163]:
array = np.random.randint(0,5,(10,10))
block_side_size = 3
i = 1 + (array.shape[0]-3)
j = 1 + (array.shape[1]-3)
blocks = stride_tricks.as_strided(array, shape=(i, j, block_side_size, block_side_size), strides=array.strides + array.strides)
print(blocks)

[[[[2 4 0]
   [1 3 0]
   [4 2 1]]

  [[4 0 1]
   [3 0 3]
   [2 1 3]]

  [[0 1 1]
   [0 3 1]
   [1 3 1]]

  [[1 1 0]
   [3 1 1]
   [3 1 2]]

  [[1 0 0]
   [1 1 2]
   [1 2 3]]

  [[0 0 4]
   [1 2 3]
   [2 3 3]]

  [[0 4 1]
   [2 3 1]
   [3 3 1]]

  [[4 1 0]
   [3 1 3]
   [3 1 0]]]


 [[[1 3 0]
   [4 2 1]
   [0 0 3]]

  [[3 0 3]
   [2 1 3]
   [0 3 0]]

  [[0 3 1]
   [1 3 1]
   [3 0 0]]

  [[3 1 1]
   [3 1 2]
   [0 0 1]]

  [[1 1 2]
   [1 2 3]
   [0 1 2]]

  [[1 2 3]
   [2 3 3]
   [1 2 0]]

  [[2 3 1]
   [3 3 1]
   [2 0 3]]

  [[3 1 3]
   [3 1 0]
   [0 3 1]]]


 [[[4 2 1]
   [0 0 3]
   [1 2 2]]

  [[2 1 3]
   [0 3 0]
   [2 2 4]]

  [[1 3 1]
   [3 0 0]
   [2 4 2]]

  [[3 1 2]
   [0 0 1]
   [4 2 3]]

  [[1 2 3]
   [0 1 2]
   [2 3 1]]

  [[2 3 3]
   [1 2 0]
   [3 1 0]]

  [[3 3 1]
   [2 0 3]
   [1 0 2]]

  [[3 1 0]
   [0 3 1]
   [0 2 3]]]


 [[[0 0 3]
   [1 2 2]
   [0 0 1]]

  [[0 3 0]
   [2 2 4]
   [0 1 3]]

  [[3 0 0]
   [2 4 2]
   [1 3 3]]

  [[0 0 1]
   [4 2 3]
   [3 3 2]]

  [[0 1 2]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [164]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(array):
    return np.asarray(array + array.T - np.diag(array.diagonal())).view(Symetric)

sym_matrix = symetric(np.random.randint(0,10,(5,5)))
sym_matrix[2,3] = 42
print(sym_matrix)

[[ 1  6  6 10 13]
 [ 6  6 10 16 15]
 [ 6 10  7 42  7]
 [10 16 42  4  5]
 [13 15  7  5  5]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [165]:

matrices_count = 10
matrix_size = 20

matrices = np.ones((matrices_count,matrix_size,matrix_size))
vectors = np.ones((matrices_count,matrix_size,1))
tensor_dots = np.tensordot(matrices, vectors, axes=[[0, 2], [0, 1]])
print(tensor_dots)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [166]:
matrix = np.ones((16,16))
block_side_size = 4
block = np.add.reduceat(np.add.reduceat(matrix, np.arange(0, matrix.shape[0], block_side_size), axis=0),
                                            np.arange(0, matrix.shape[1], block_side_size), axis=1)
print(block)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [172]:
import sys

def iterate(matrix):
    neighbours_count = (matrix[0:-2,0:-2] + matrix[0:-2,1:-1] + matrix[0:-2,2:] +
                        matrix[1:-1,0:-2]                     + matrix[1:-1,2:] +
                        matrix[2:  ,0:-2] + matrix[2:  ,1:-1] + matrix[2:  ,2:])

    # Apply rules
    birth = (neighbours_count==3) & (matrix[1:-1,1:-1]==0)
    survive = ((neighbours_count==2) | (neighbours_count==3)) & (matrix[1:-1,1:-1]==1)
    matrix[...] = 0
    matrix[1:-1,1:-1][birth | survive] = 1
    return matrix

matrix = np.random.randint(0,2,(50,50))
for i in range(100):
    matrix = iterate(matrix)
    

np.set_printoptions(threshold=sys.maxsize)

print(matrix)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0
  0 0 1 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0
  0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0

#### 89. How to get the n largest values of an array (★★★)

In [174]:
array = np.arange(5001)
np.random.shuffle(array)
n = 5

print (array[np.argpartition(-array,n)[:n]])

[4999 4996 4998 4997 5000]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [175]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [176]:
array = np.array([("Hello", 2.5, 3),
                  ("World", 3.6, 2)])
record_array = np.core.records.fromarrays(array.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(record_array)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [182]:

x = np.random.rand(1000000)

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

18.6 ms ± 269 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
4.44 ms ± 47.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
2.32 ms ± 163 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [184]:
array_A = np.random.randint(0,5,(8,3))
array_B = np.random.randint(0,5,(2,2))

C = (array_A[..., np.newaxis, np.newaxis] == array_B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[2 3 5 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [187]:
matrix = np.random.randint(0,5,(10,3))
print(matrix)

equal_rows = np.all(matrix[:,1:] == matrix[:,:-1], axis=1)
unequal_rows = matrix[~equal_rows]

print(unequal_rows)

[[2 0 2]
 [0 2 1]
 [1 4 1]
 [1 2 2]
 [0 0 1]
 [2 0 1]
 [2 1 4]
 [3 2 2]
 [4 4 1]
 [0 2 3]]
[[2 0 2]
 [0 2 1]
 [1 4 1]
 [1 2 2]
 [0 0 1]
 [2 0 1]
 [2 1 4]
 [3 2 2]
 [4 4 1]
 [0 2 3]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [188]:
vector = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(vector[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [190]:
array = np.random.randint(0,2,(6,3))
print(array)
unique = np.unique(array, axis=0)
print(unique)

[[0 0 0]
 [1 0 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]
 [0 0 1]]
[[0 0 0]
 [0 0 1]
 [1 0 0]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [191]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       
np.einsum('i,i->i', A, B) 
np.einsum('i,i', A, B)    
np.einsum('i,j->ij', A, B)   

array([[5.90922051e-01, 2.61883932e-01, 3.40204789e-03, 6.50527003e-01,
        8.58465900e-01, 4.82061953e-02, 3.89181308e-02, 7.28488386e-02,
        5.68877497e-01, 2.62029959e-01],
       [3.52971196e-01, 1.56429236e-01, 2.03212067e-03, 3.88574591e-01,
        5.12781229e-01, 2.87946581e-02, 2.32466857e-02, 4.35142700e-02,
        3.39803482e-01, 1.56516460e-01],
       [1.37495330e-01, 6.09349706e-02, 7.91586129e-04, 1.51364169e-01,
        1.99747247e-01, 1.12165839e-02, 9.05544352e-03, 1.69504169e-02,
        1.32366019e-01, 6.09689479e-02],
       [1.79977906e-01, 7.97623335e-02, 1.03616620e-03, 1.98131864e-01,
        2.61464087e-01, 1.46822243e-02, 1.18533463e-02, 2.21876665e-02,
        1.73263767e-01, 7.98068089e-02],
       [5.40271639e-01, 2.39436760e-01, 3.11044407e-03, 5.94767600e-01,
        7.84883180e-01, 4.40742397e-02, 3.55822943e-02, 6.66046585e-02,
        5.20116616e-01, 2.39570270e-01],
       [9.12203344e-02, 4.04268885e-02, 5.25172391e-04, 1.00421520e-01,
   

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [193]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 

r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                
r_int = np.linspace(0, r.max(), 200)
print(r_int)
x_int = np.interp(r_int, r, x)
print(x_int)
y_int = np.interp(r_int, r, y)
print(y_int)

[  0.           2.48788858   4.97577716   7.46366574   9.95155432
  12.43944289  14.92733147  17.41522005  19.90310863  22.39099721
  24.87888579  27.36677437  29.85466295  32.34255152  34.8304401
  37.31832868  39.80621726  42.29410584  44.78199442  47.269883
  49.75777158  52.24566016  54.73354873  57.22143731  59.70932589
  62.19721447  64.68510305  67.17299163  69.66088021  72.14876879
  74.63665736  77.12454594  79.61243452  82.1003231   84.58821168
  87.07610026  89.56398884  92.05187742  94.539766    97.02765457
  99.51554315 102.00343173 104.49132031 106.97920889 109.46709747
 111.95498605 114.44287463 116.9307632  119.41865178 121.90654036
 124.39442894 126.88231752 129.3702061  131.85809468 134.34598326
 136.83387184 139.32176041 141.80964899 144.29753757 146.78542615
 149.27331473 151.76120331 154.24909189 156.73698047 159.22486904
 161.71275762 164.2006462  166.68853478 169.17642336 171.66431194
 174.15220052 176.6400891  179.12797768 181.61586625 184.10375483
 186.59164341

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [194]:
matrix = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(matrix, 1) == 0, axis=-1)
M &= (matrix.sum(axis=-1) == n)
print(matrix[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [195]:
array = np.random.randn(100) 
replacement_count = 1000 

idx = np.random.randint(0, array.size, (replacement_count, array.size))
means = array[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])

print(confint)

[-0.20410564  0.16661151]
